development:
  adapter: postgresql
  encoding: unicode
  database: ka-pian-dev
  username: kapian
  password: kapian
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: ka-pian-prod